### ISSUE TITLE
[BUG] hitting `replaceAll is not a function` error on Android mobile devices

### ISSUE THREAD

**Issue by smhutch** [family/connectkit#173]
**Describe the bug**

We're seeing some exceptions on mobile devices, and the error seems to be coming from connecKit.

```
TypeError: n.replaceAll is not a function
  at <anonymous>(./node_modules/connectkit/build/index.es.js:3729:1)
  at Array.forEach(<anonymous>)
  at uc(./node_modules/connectkit/build/index.es.js:3729:1)
  at <anonymous>(./node_modules/connectkit/build/index.es.js:3729:1)
  at Array.map(<anonymous>)
  at uu(./node_modules/connectkit/build/index.es.js:3729:1)
  at ux(./node_modules/connectkit/build/index.es.js:3729:1)
  at aD(app:///_next/static/chunks/framework-6397aa3657684b00.js:9:61585)
  at i(app:///_next/static/chunks/framework-6397aa3657684b00.js:9:119733)
  at o3(app:///_next/static/chunks/framework-6397aa3657684b00.js:9:107168)
  at o1(app:///_next/static/chunks/framework-6397aa3657684b00.js:9:107096)
  at o0(app:///_next/static/chunks/framework-6397aa3657684b00.js:9:106959)
  at oB(app:///_next/static/chunks/framework-6397aa3657684b00.js:9:103746)
  at oj(app:///_next/static/chunks/framework-6397aa3657684b00.js:9:102301)
  at x(app:///_next/static/chunks/framework-6397aa3657684b00.js:33:1374)
  at MessagePort.T(app:///_next/static/chunks/framework-6397aa3657684b00.js:33:1904)
```

**To reproduce**

Unsure. I haven't been able to replicate yet.

**Expected behavior**

No exception

**Screenshots**

Some screenshots from our Sentry error reporting for this exception:

![CleanShot 2023-03-24 at 08 55 21](https://user-images.githubusercontent.com/7217244/227472184-2e5b5dd6-8a04-4be9-8151-5bf96a527ffd.png)

**Environment details**

![CleanShot 2023-03-24 at 08 59 30](https://user-images.githubusercontent.com/7217244/227472874-d6e11ddb-d921-47ed-8fa5-eff0df76a29d.png)

**Additional context**

This isn't a major issue, but would be nice to clean up to avoid noise in our error reporting. Thanks!

**Comment by lochie** [comment]
we'll probably have a fix for in the next release of connectkit.

we recently became aware that this occurs on older versions of nodejs that don't support `replaceAll`, which we use in our localisations setup. we've just been discussing internally if we should adjust the code to not use `replaceAll`, or just force nodejs to a supportive version. of course the former is more ideal so we support more versions of nodejs and dont require anyone to do any updates on their end.

**Comment by lochie** [comment]
just [merged a fix](https://github.com/family/connectkit/commit/c8d69fe6f5f4c1afe80a454687fc783d2d89c212) for this, will be ready the next release
