### ISSUE TITLE
[BUG] wagmi not recognized in nextjs example

### ISSUE THREAD

**Issue by keon** [family/connectkit#30]
I simply ran `yarn build` and `yarn dev:nextjs` after cloning the library.
Other examples work fine, but nextjs example doesn't seem to recognize wagmi library.

```
error - ../../packages/connectkit/build/index.js (120:0) @ eval
error - TypeError: Cannot read properties of undefined (reading 'mainnet')
    at eval (webpack-internal:///../../packages/connectkit/build/index.js:120:17)
    at Object.../../packages/connectkit/build/index.js (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:186:1)
    at __webpack_require__ (/Users/keon/om/connectkit/examples/nextjs/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.tsx:11:68)
    at Object../pages/_app.tsx (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/keon/om/connectkit/examples/nextjs/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:669:39)
    at /Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:670:28
    at Object.<anonymous> (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:673:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  page: '/'
}
  118 | var getAppName = function () { return globalAppName; };
  119 | var defaultChains = [
> 120 |     wagmi.chain.mainnet,
  121 |     wagmi.chain.polygon,
  122 |     wagmi.chain.optimism,
  123 |     wagmi.chain.arbitrum,
event - compiled client and server successfully in 462 ms (1326 modules)
TypeError: Cannot read properties of undefined (reading 'mainnet')
    at eval (webpack-internal:///../../packages/connectkit/build/index.js:120:17)
    at Object.../../packages/connectkit/build/index.js (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:186:1)
    at __webpack_require__ (/Users/keon/om/connectkit/examples/nextjs/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.tsx:11:68)
    at Object../pages/_app.tsx (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/keon/om/connectkit/examples/nextjs/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:669:39)
    at /Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:670:28
    at Object.<anonymous> (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:673:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
TypeError: Cannot read properties of undefined (reading 'mainnet')
    at eval (webpack-internal:///../../packages/connectkit/build/index.js:120:17)
    at Object.../../packages/connectkit/build/index.js (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:186:1)
    at __webpack_require__ (/Users/keon/om/connectkit/examples/nextjs/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.tsx:11:68)
    at Object../pages/_app.tsx (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/Users/keon/om/connectkit/examples/nextjs/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:669:39)
    at /Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:670:28
    at Object.<anonymous> (/Users/keon/om/connectkit/examples/nextjs/.next/server/pages/_app.js:673:3)
```

**Comment by lochie** [comment]
hey @keon, thanks for calling this out.
it looks like this was an issue with the react types version we were using. i've made a PR to fix this (#31), now just waiting for another maintainer to approve
