### ISSUE TITLE
[BUG] Error: StreamMiddleware - Unknown response id "1633111594"

### ISSUE THREAD

**Issue by alexbakers** [family/connectkit#37]
**Describe the bug**

[Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64)](https://brave.com/latest/)

```bash
git clone https://github.com/family/connectkit
cd connectkit
yarn install
yarn dev:connectkit
yarn dev:vite
```

<img width="835" alt="image" src="https://user-images.githubusercontent.com/98721968/200193739-77de8e9c-7575-4b98-9fc4-7cd2f8b6f7cc.png">

```
inpage.js:1 Error: StreamMiddleware - Unknown response id "1633111594"
    at l._handleDisconnect (inpage.js:1:38557)
    at l._handleDisconnect (inpage.js:1:42154)
    at l._handleStreamDisconnect (inpage.js:1:46283)
    at inpage.js:17:12354
    at t (inpage.js:17:8407)
    at d.<anonymous> (inpage.js:17:11676)
    at d.t (inpage.js:17:8407)
    at d.h (inpage.js:8:27815)
    at d (inpage.js:8:21053)
    at s.emit (inpage.js:8:24049)
```

**Comment by alexbakers** [comment]
This error occurs if you have 2 versions of Metamask installed.

<img width="150" alt="image" src="https://user-images.githubusercontent.com/98721968/200203007-0df00a5a-21a8-4f2a-8df0-93830482dcbd.png">
